import { AiOutlineDelete } from "react-icons/ai";
import { BiHelpCircle } from "react-icons/bi";
import {
  FiAlertCircle,
  FiAlertTriangle,
  FiAperture,
  FiArrowLeft,
  FiArrowRight,
  FiAtSign,
  FiCheck,
  FiCheckCircle,
  FiCheckSquare,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiCircle,
  FiCode,
  FiCopy,
  FiFile,
  FiFileText,
  FiFolder,
  FiGithub,
  FiGlobe,
  FiGrid,
  FiHardDrive,
  FiHeart,
  FiHome,
  FiImage,
  FiInfo,
  FiLinkedin,
  FiLoader,
  FiMaximize,
  FiMenu,
  FiMessageSquare,
  FiMinimize,
  FiMinus,
  FiMoreHorizontal,
  FiPlus,
  FiPower,
  FiRss,
  FiSave,
  FiSearch,
  FiSettings,
  FiShare2,
  FiSidebar,
  FiSliders,
  FiSquare,
  FiTerminal,
  FiTool,
  FiTrendingDown,
  FiTrendingUp,
  FiUser,
  FiX,
} from "react-icons/fi";
import { GrArticle, GrGamepad, GrUserExpert, GrUserNew } from "react-icons/gr";
import { TbAddressBook, TbAsteriskSimple, TbComponents } from "react-icons/tb";
import { VscLinkExternal, VscWindow } from "react-icons/vsc";

export const IconsMap = {
  anonymousUser: GrUserNew,
  apps: FiGrid,
  article: GrArticle,
  asterisk: TbAsteriskSimple,
  back: FiArrowLeft,
  checkCircle: FiCheckCircle,
  checkSquare: FiCheckSquare,
  circle: FiCircle,
  code: FiCode,
  comment: FiMessageSquare,
  construction: FiTool,
  contact: TbAddressBook,
  copy: FiCopy,
  cross: FiX,
  delete: AiOutlineDelete,
  desktop: VscWindow,
  dir: FiFolder,
  dislike: FiTrendingDown,
  down: FiChevronDown,
  email: FiAtSign,
  error: FiAlertCircle,
  explorer: FiHardDrive,
  file: FiFile,
  filter: FiSliders,
  forward: FiArrowRight,
  game: GrGamepad,
  github: FiGithub,
  globe: FiGlobe,
  heart: FiHeart,
  help: BiHelpCircle,
  home: FiHome,
  image: FiImage,
  info: FiInfo,
  left: FiChevronLeft,
  like: FiTrendingUp,
  linkExternal: VscLinkExternal,
  linkedIn: FiLinkedin,
  loader: FiLoader,
  maximize: FiMaximize,
  menu: FiMenu,
  minimize: FiMinus,
  moreHorizontal: FiMoreHorizontal,
  plus: FiPlus,
  power: FiPower,
  preview: FiAperture,
  registeredUser: GrUserExpert,
  restoreMaximize: FiMinimize,
  right: FiChevronRight,
  rss: FiRss,
  save: FiSave,
  search: FiSearch,
  settings: FiSettings,
  share: FiShare2,
  sidebar: FiSidebar,
  square: FiSquare,
  success: FiCheck,
  terminal: FiTerminal,
  textFile: FiFileText,
  user: FiUser,
  warn: FiAlertTriangle,
  storybook: TbComponents,
};

export type IconName = keyof typeof IconsMap | "";
