scalar Date
scalar Email

directive @required(required: Boolean = true) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION

directive @constraint(
  # String constraints
  minLength: Int
  maxLength: Int
  length: Int
  pattern: String
  format: String

  # Number constraints
  min: Float
  max: Float
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION

type Error {
  code: String!
  message: String!
  status: Int
}

enum OpStatus {
  Error
  Success
}

type OperationResult {
  status: OpStatus!
  error: Error
}

input Pagination {
  page: Int! @required
  count: Int
}
